name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: jery04
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to output branch
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout -b output || git checkout output
          cp -r dist/* .
          git add .
          git commit -m "Snake animation updated" --allow-empty
          git push origin output -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

